- apt: pkg={{item}} state=latest update_cache=yes cache_valid_time=3600
  with_items: [unzip]

- stat: path={{phantomjs_bin_path}}
  register: phantomjs_bin_stats

- file: path={{phantomjs_download_dir}}
        state=directory
  when: not phantomjs_bin_stats.stat.exists

- get_url: url={{phantomjs_url}}
           dest={{phantomjs_download_path}}
  when: not phantomjs_bin_stats.stat.exists

- shell: 'cd {{phantomjs_download_dir}} && tar xvf {{phantomjs_download_path}}'
  when: not phantomjs_bin_stats.stat.exists

- command: cp {{phantomjs_download_bin_path}} {{phantomjs_bin_path}}
  when: not phantomjs_bin_stats.stat.exists

- file: path={{phantomjs_bin_path}}
        mode=0755

- file: dest=/usr/local/bin/phantomjs
        src={{phantomjs_bin_path}}
        state=link
